### ISSUE TITLE
[FEATURE REQUEST] - add a RAM and disk usage display for screenfetch 

### ISSUE THREAD

**Issue by barnacl437** [SegoCode/DebloBat#9]
### Feature Description

Just add a RAM display for the system information screenfetch, may follow the used/total scheme like the original neofetch. Also disk usage if it's possible to detect disks and their current usage.

![image](https://github.com/SegoCode/DebloBat/assets/87983017/d4e80aaf-490f-4a54-b028-7ff2a900fe7c)

### Motivation

Actually I feel it a bit lacking if it does not display RAM. 
It's an important factor that may be able to represent system status and thus people can check their RAM usage to see if debloating process is success without opening other monitoring tools, in other say, for convenient's sake.

### Confirmation

- [X] I performed a [search of the feature requests](https://github.com/segocode/Deblobat/issues) to avoid suggesting a duplicate feature
- [X] I understand that not filling out this template correctly may lead to the request being closed

**Comment by SegoCode** [comment]
![imagen](https://github.com/SegoCode/DebloBat/assets/35817798/9d4a69c8-c988-48b1-98bb-861ec2c7a421)

Done
